### ISSUE TITLE
Crash on viewing weekly stats

### ISSUE THREAD

**Issue by johnmbklein** [KnockSoftware/RideReportIssues#13]
>I can't view weekly data - the app crashes every time I try.
===================== 
Support Id: 34a06619-749b-4237-8725-c4bc7af6500d 
Version:1.7 (139) 
iOS Version: 10.3.1 
iPhone Model: iPhone9,2

**Comment by ezheidtmann** [comment]
@quicklywilliam Let me know if there are server changes that would be helpful

**Comment by johnmbklein** [comment]
I've gotten a few more reports of this crash.

One user mentioned being new and having > 1 week of usage. Related?

652182b0-7c7d-477a-a83d-33dd4af3b28d

**Comment by quicklywilliam** [comment]
This is being tracked by https://github.com/KnockSoftware/Ride/issues/363
