### ISSUE TITLE
Eichelberger didn't get his imperial century trophy

### ISSUE THREAD

**Issue by quicklywilliam** [KnockSoftware/RideReportIssues#26]
100 mile day but missing a trophy for this stat-trophy:
https://ride.report/admin/ride/stattrophy/5a0d90de-c85f-425f-85b6-5368ba9ab8a1/change/

Understandable he's devastated.

![img_0113](https://cloud.githubusercontent.com/assets/2109/26031279/1a53d0e2-3822-11e7-9cc2-526b8f81296e.PNG)
![img_0112](https://cloud.githubusercontent.com/assets/2109/26031286/1d3bb4f0-3822-11e7-914d-81b32943b777.PNG)
![img_0111](https://cloud.githubusercontent.com/assets/2109/26031287/20efb470-3822-11e7-9407-2c1cf5c2ea13.PNG)

**Comment by ezheidtmann** [comment]
His 15 mile trip is recorded as 2.8 miles on the server. It looks we got a small PUT during a trip pause, then a big PUT much later (after another trip or two).

Is it possible that the iOS client is not uploading length when it uploads locations?

I thought I fixed it so the server would use the client-provided length but I'm writing tests to verify.

**Comment by ezheidtmann** [comment]
Verified that the server is doing everything right AFAICT here: we're accepting the length the client gives us and using it in trophy math. And according to that data, 12 miles of his big day didn't happen. :-/

**Comment by quicklywilliam** [comment]
Ah, got it. So this should be fixed by https://github.com/KnockSoftware/Ride/commit/3ac14fcc287947ef9982b9b555f9bfceeac7c6a1

**Comment by quicklywilliam** [comment]
@ezheidtmann can you confirm that this can be closed?

**Comment by ezheidtmann** [comment]
I'm not following the logic from that bug to that fix, but if it is indeed a fix then I think we're good.

**Comment by quicklywilliam** [comment]
Confirmed offline that this is indeed fixed in next iOS update.
